### ISSUE TITLE
目录建议

### ISSUE THREAD

**Issue by manhua-man** [OTFCG/Awesome-Game-Analysis#56]
目录是否以引擎或者年份来进行排序效果更好。以年份举例 ，2023 年的游戏在目录顶层，相对来说 2023 年的技术应该要比 2018 2013年的游戏技术更先进。

**Comment by K1ngst0m** [comment]
Thank you for your suggestion. It would be a good fit for a simple sort by year in markdown. We are considering creating a GitHub page to put our table and enable filtering and sorting.
